[features]
experimental_use_rmcp_client = true

[mcp_servers.container-use]
startup_timeout_sec = 60
command = "container-use"
args = ["stdio"]
env = {}

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
bearer_token_env_var = "LINEAR_API_KEY"

[mcp_servers.render]
url = "https://mcp.render.com/mcp"
bearer_token_env_var = "RENDER_API_KEY"

[mcp_servers."github-mcp"]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_PERSONAL_ACCESS_TOKEN"
