import { dag, Container, Directory, Secret, object, func, argument } from "@dagger.io/dagger"

/**
 * Operator contract (PLAN-180, PLAN-191):
 *
 *   bootstrap  Phase 0 — prerequisites only. Creates SA, GCS bucket, SSH keypair.
 *              Never touches Terraform-owned resources. Idempotent.
 *   plan       Phase 1 — non-mutating. terraform plan, print diff, exit.
 *   check      Phase 1 — ephemeral only. Terratest suite, isolated resources.
 *   deploy     Phase 2 — production-mutating. terraform apply + SSH bootstrap.
 *   verify     Phase 3 — non-mutating. External smoke checks.
 *   destroy    Phase 2 — production-mutating. terraform destroy.
 *
 * GCP auth modes (PLAN-192):
 *
 *   Preferred  — host ADC: omit gcpCredentials. Dagger mounts ~/.config/gcloud.
 *                bootstrap() creates the deploy SA and emits deploy-key.json.
 *   Fallback   — pass gcpCredentials explicitly (CI / pre-minted key).
 *
 * Secrets (PLAN-181):
 *
 *   gcpCredentials  — optional. SA JSON key. Omit to use host ADC.
 *   cloudflareToken — always required. No ADC equivalent.
 *   sshPublicKey    — Terraform only. Generated by bootstrap if absent.
 *   sshPrivateKey   — deploy only. Generated by bootstrap if absent.
 */
@object()
export class TidelaneInfra {
  /**
   * bootstrap — control-plane prerequisites only (Phase 0).
   *
   * Uses the host gcloud identity (ADC) to:
   *   1. Verify auth context
   *   2. Create deploy service account (tidelane-deploy@<project>)
   *   3. Apply required IAM bindings
   *   4. Create GCS state bucket with versioning
   *   5. Mint deploy SA JSON key → infra/.deploy-key.json
   *   6. Validate Cloudflare token and resolve zone ID
   *   7. Generate SSH keypair → infra/.tidelane / infra/.tidelane.pub
   *
   * All steps are idempotent. Failures emit the exact remediation command.
   *
   * After bootstrap, use the emitted "Next step:" command to run plan.
   */
  @func()
  async bootstrap(
    src: Directory,
    cloudflareToken: Secret,
    gcpProject: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "us-central1" }) gcpRegion: string,
    @argument({ defaultValue: "tidelane-deploy" }) serviceAccountName: string,
    @argument({ defaultValue: "" }) backendBucket: string,
  ): Promise<string> {
    const resolvedBucket = backendBucket || `${gcpProject}-tidelane-state`
    const script = src.file("scripts/bootstrap-prereqs.sh")

    const result = await dag.container()
      .from("google/cloud-sdk:slim")
      .withExec(["apt-get", "install", "-y", "--no-install-recommends", "openssh-client", "curl"])
      // Mount host gcloud config for ADC (preferred auth path).
      .withMountedDirectory("/root/.config/gcloud", dag.host().directory(`${process.env.HOME}/.config/gcloud`))
      .withMountedFile("/bootstrap-prereqs.sh", script)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withEnvVariable("GCP_PROJECT", gcpProject)
      .withEnvVariable("GCP_REGION", gcpRegion)
      .withEnvVariable("SA_NAME", serviceAccountName)
      .withEnvVariable("BACKEND_BUCKET", resolvedBucket)
      .withEnvVariable("DOMAIN", domain)
      .withExec(["bash", "/bootstrap-prereqs.sh"])
      .stdout()

    // Export generated files to infra/ on the host.
    const ctr = dag.container()
      .from("google/cloud-sdk:slim")
      .withExec(["apt-get", "install", "-y", "--no-install-recommends", "openssh-client", "curl"])
      .withMountedDirectory("/root/.config/gcloud", dag.host().directory(`${process.env.HOME}/.config/gcloud`))
      .withMountedFile("/bootstrap-prereqs.sh", script)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withEnvVariable("GCP_PROJECT", gcpProject)
      .withEnvVariable("GCP_REGION", gcpRegion)
      .withEnvVariable("SA_NAME", serviceAccountName)
      .withEnvVariable("BACKEND_BUCKET", resolvedBucket)
      .withEnvVariable("DOMAIN", domain)
      .withExec(["bash", "/bootstrap-prereqs.sh"])

    await ctr.file("/output/deploy-key.json").export("infra/.deploy-key.json")
    await ctr.file("/output/tidelane").export("infra/.tidelane")
    await ctr.file("/output/tidelane.pub").export("infra/.tidelane.pub")
    await ctr.file("/output/zone-id.txt").export("infra/.zone-id.txt")

    return result
  }

  /**
   * plan — non-mutating.
   * Runs `terraform plan` and prints the diff. Never writes state.
   */
  @func()
  async plan(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "plan",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .stdout()
  }

  /**
   * deploy — production-mutating.
   * Runs `terraform apply`, emits outputs as JSON.
   * Post-apply smallweb bootstrap handled in PLAN-186.
   */
  @func()
  async deploy(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "apply", "-auto-approve",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .withExec(["terraform", "output", "-json"])
      .stdout()
  }

  /**
   * destroy — production-mutating.
   * Runs `terraform destroy` against production state.
   */
  @func()
  async destroy(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "destroy", "-auto-approve",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .stdout()
  }

  /**
   * verify — non-mutating. Extended smoke checks implemented in PLAN-187.
   */
  @func()
  async verify(
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
  ): Promise<string> {
    return dag.container()
      .from("curlimages/curl:latest")
      .withExec(["curl", "-sf", "--max-time", "15", `https://${domain}`])
      .stdout()
  }

  /**
   * check — ephemeral-only (net non-mutating).
   * Runs Terratest suite against isolated tidelane-test-<hex> resources.
   * Always destroys on exit. Pass preserveOnFailure=true to keep on failure.
   * Full suite implemented in PLAN-185.
   */
  @func()
  async check(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: false }) preserveOnFailure: boolean,
  ): Promise<string> {
    let ctr = dag.container()
      .from("golang:1.22-bookworm")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withEnvVariable("GCP_PROJECT", gcpProject)
      .withEnvVariable("CLOUDFLARE_ZONE_ID", cloudflareZoneId)
      .withEnvVariable("PRESERVE_ON_FAILURE", preserveOnFailure ? "1" : "0")

    if (gcpCredentials !== null) {
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", gcpCredentials)
    } else {
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr
      .withWorkdir("/workspace/test")
      .withExec(["go", "mod", "tidy"])
      .withExec(["go", "test", "-v", "-timeout", "30m", "./..."])
      .stdout()
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * tfInit returns a Terraform container initialised against the GCS backend.
   *
   * gcpCredentials=null → ADC mode: mounts host ~/.config/gcloud.
   * gcpCredentials set  → key mode: sets GOOGLE_CREDENTIALS env var.
   */
  private tfInit(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
  ): Container {
    let ctr = dag.container()
      .from("hashicorp/terraform:1.7")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withSecretVariable("TF_VAR_ssh_public_key", sshPublicKey)
      .withWorkdir("/workspace/terraform")

    if (gcpCredentials !== null) {
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", gcpCredentials)
    } else {
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr.withExec([
      "terraform", "init", "-reconfigure",
      `-backend-config=bucket=${backendBucket}`,
      `-backend-config=prefix=${backendPrefix}`,
    ])
  }
}
