import { dag, Container, Directory, Secret, object, func, argument } from "@dagger.io/dagger"

/**
 * Operator contract (PLAN-180):
 *
 *   bootstrap  Phase 0 — prerequisites only. Creates SA, GCS bucket, SSH keypair.
 *              Never touches compute or DNS. Idempotent. Elevated authority required.
 *   plan       Phase 1 — non-mutating: terraform plan, print diff, exit
 *   check      Phase 1 — ephemeral-only: Terratest suite, create/destroy test resources
 *   deploy     Phase 2 — production-mutating: terraform apply + smallweb SSH bootstrap
 *   verify     Phase 3 — non-mutating: external smoke checks against tidelands.dev
 *   destroy    Phase 2 — production-mutating: terraform destroy
 *
 * Secrets contract (PLAN-181, updated PLAN-192):
 *
 *   gcpCredentials  — GCP service account JSON key. OPTIONAL: omit to use host
 *                     ADC (gcloud volume mount). Required in CI/key-fallback mode.
 *   cloudflareToken — Cloudflare API token (DNS edit + zone settings). Always required.
 *   sshPublicKey    — SSH public key → instance metadata. Generated by bootstrap if absent.
 *   sshPrivateKey   — SSH private key for SSH bootstrap. Generated by bootstrap if absent.
 *
 * GCP auth modes (PLAN-192):
 *   Preferred  — host ADC via ~/.config/gcloud volume mount. bootstrap() creates
 *                the deploy SA and returns a JSON key for subsequent commands.
 *   Fallback   — pass gcpCredentials explicitly (CI or pre-minted key path).
 *
 * All non-secret config (backendBucket, backendPrefix, gcpProject, etc.)
 * flows in as plain string args.
 */
@object()
export class TidelaneInfra {
  /**
   * bootstrap — control-plane prerequisites only (Phase 0).
   *
   * Creates the prerequisites that plan/deploy require, without touching
   * any Terraform-owned resources (compute, DNS, firewall).
   *
   * What it may create:
   *   - GCP service account for deploy operations
   *   - IAM bindings on that SA
   *   - GCS bucket for Terraform state
   *   - Service account JSON key
   *   - SSH keypair for instance access
   *
   * All operations are idempotent. Failures include the exact remediation
   * command needed to resolve the issue.
   *
   * Implemented in PLAN-193.
   */
  @func()
  async bootstrap(
    gcpProject: string,
    cloudflareToken: Secret,
    @argument({ defaultValue: "us-central1" }) gcpRegion: string,
    @argument({ defaultValue: "tidelane-deploy" }) serviceAccountName: string,
    @argument({ defaultValue: "" }) backendBucket: string,
  ): Promise<string> {
    // TODO(PLAN-193): implement via gcloud prerequisite creation
    throw new Error("bootstrap not yet implemented — see PLAN-193")
  }

  /**
   * plan — non-mutating.
   * Runs `terraform plan` and prints the diff. Never writes state.
   */
  @func()
  async plan(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "plan",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .stdout()
  }

  /**
   * deploy — production-mutating.
   * Runs `terraform apply`, emits outputs as JSON.
   * Post-apply smallweb bootstrap is handled in PLAN-186.
   */
  @func()
  async deploy(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "apply", "-auto-approve",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .withExec(["terraform", "output", "-json"])
      .stdout()
  }

  /**
   * destroy — production-mutating.
   * Runs `terraform destroy` against production state.
   */
  @func()
  async destroy(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
    gcpProject: string,
    cloudflareZoneId: string,
    @argument({ defaultValue: "us-central1-a" }) gcpZone: string,
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
    @argument({ defaultValue: "tidelane-smallweb" }) instanceName: string,
  ): Promise<string> {
    return this.tfInit(src, gcpCredentials, cloudflareToken, sshPublicKey, backendBucket, backendPrefix)
      .withExec([
        "terraform", "destroy", "-auto-approve",
        `-var=gcp_project_id=${gcpProject}`,
        `-var=gcp_zone=${gcpZone}`,
        `-var=domain=${domain}`,
        `-var=cloudflare_zone_id=${cloudflareZoneId}`,
        `-var=instance_name=${instanceName}`,
      ])
      .stdout()
  }

  /**
   * verify — non-mutating.
   * Hits the domain externally and asserts a 200 response.
   * Extended smoke checks are implemented in PLAN-187.
   */
  @func()
  async verify(
    @argument({ defaultValue: "tidelands.dev" }) domain: string,
  ): Promise<string> {
    return dag.container()
      .from("curlimages/curl:latest")
      .withExec(["curl", "-sf", "--max-time", "15", `https://${domain}`])
      .stdout()
  }

  /**
   * check — ephemeral-only (net non-mutating).
   * Runs Terratest suite against isolated resources named tidelane-test-<hex>.
   * Always destroys on exit. Pass preserveOnFailure=true to skip destroy on failure.
   * Full suite implemented in PLAN-185.
   */
  @func()
  async check(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    gcpProject: string,
    @argument({ defaultValue: false }) preserveOnFailure: boolean,
  ): Promise<string> {
    let ctr = dag.container()
      .from("golang:1.22-bookworm")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)

    if (gcpCredentials !== null) {
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", gcpCredentials)
    } else {
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr
      .withEnvVariable("GCP_PROJECT", gcpProject)
      .withEnvVariable("PRESERVE_ON_FAILURE", preserveOnFailure ? "1" : "0")
      .withWorkdir("/workspace/test")
      .withExec(["go", "test", "-v", "-timeout", "30m", "./..."])
      .stdout()
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * tfInit returns a container with Terraform initialised against the GCS backend.
   *
   * gcpCredentials: when null, mounts host gcloud config for ADC. When provided,
   * sets GOOGLE_CREDENTIALS directly (key-fallback / CI mode).
   */
  private tfInit(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    backendBucket: string,
    backendPrefix: string,
  ): Container {
    let ctr = dag.container()
      .from("hashicorp/terraform:1.7")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withSecretVariable("TF_VAR_ssh_public_key", sshPublicKey)

    if (gcpCredentials !== null) {
      // Key-fallback mode: explicit service account JSON key.
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", gcpCredentials)
    } else {
      // Host-auth (ADC) mode: mount the host gcloud config so the GCP SDK and
      // Terraform provider resolve credentials via Application Default Credentials.
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr
      .withWorkdir("/workspace/terraform")
      .withExec([
        "terraform", "init", "-reconfigure",
        `-backend-config=bucket=${backendBucket}`,
        `-backend-config=prefix=${backendPrefix}`,
      ])
  }
}
