import { dag, Container, Directory, Secret, File, object, func, argument } from "@dagger.io/dagger"

type DeploymentConfig = {
  backendBucket: string
  backendPrefix: string
  gcpProject: string
  cloudflareZoneId: string
  gcpZone: string
  domain: string
  instanceName: string
  deploymentSlot: string
  manageDirectDnsRecords: boolean
}

type SmallwebRootConfig = {
  apps?: Record<string, {
    authorizedEmails?: string[]
    [key: string]: unknown
  }>
  [key: string]: unknown
}

/**
 * Operator contract (PLAN-180):
 *
 *   bootstrap  Phase 0 — prerequisites only. Creates SA, GCS bucket, SSH keypair.
 *              Never touches compute or DNS. Idempotent. Elevated authority required.
 *   plan       Phase 1 — non-mutating: terraform plan, print diff, exit
 *   check      Phase 1 — ephemeral-only: Terratest suite, create/destroy test resources
 *   moduleCheck Phase 1 — preview-safe module build/smoke test
 *   deploy     Phase 2 — production-mutating: terraform apply + smallweb SSH bootstrap
 *   verify     Phase 3 — non-mutating: external smoke checks against tidelands.dev
 *   destroy    Phase 2 — production-mutating: terraform destroy
 *
 * Secrets contract (PLAN-181, updated PLAN-192):
 *
 *   gcpCredentials  — GCP service account JSON key. OPTIONAL: omit to use host
 *                     ADC (gcloud volume mount). Required in CI/key-fallback mode.
 *   cloudflareToken — Cloudflare API token (DNS edit + zone settings). Always required.
 *   sshPublicKey    — SSH public key → instance metadata. Generated by bootstrap if absent.
 *   sshPrivateKey   — SSH private key for SSH bootstrap. Generated by bootstrap if absent.
 *
 * GCP auth modes (PLAN-192):
 *   Preferred  — host ADC via ~/.config/gcloud volume mount. bootstrap() creates
 *                the deploy SA and returns a JSON key for subsequent commands.
 *   Fallback   — pass gcpCredentials explicitly (CI or pre-minted key path).
 *
 * Non-secret deployment config is loaded once from env and passed down as a
 * typed object. Dagger owns the workflow surface; Terraform owns the raw vars.
 */
@object()
export class TidelaneInfra {
  /**
   * bootstrap — control-plane prerequisites only (Phase 0).
   *
   * Creates the prerequisites that plan/deploy require, without touching
   * any Terraform-owned resources (compute, DNS, firewall).
   *
   * What it may create:
   *   - GCP service account for deploy operations
   *   - IAM bindings on that SA
   *   - GCS bucket for Terraform state
   *   - Service account JSON key
   *   - SSH keypair for instance access
   *
   * All operations are idempotent. Failures include the exact remediation
   * command needed to resolve the issue.
   *
   * Implemented in PLAN-193.
   */
  @func()
  async bootstrap(
    gcpProject: string,
    cloudflareToken: Secret,
    gcpRegion = "us-central1",
    serviceAccountName = "tidelane-deploy",
    backendBucket = "",
  ): Promise<string> {
    // TODO(PLAN-193): implement via gcloud prerequisite creation
    throw new Error("bootstrap not yet implemented — see PLAN-193")
  }

  /**
   * plan — non-mutating.
   * Runs `terraform plan` and prints the diff. Never writes state.
   */
  @func()
  async plan(
    src: Directory,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    deploymentSlot = "blue",
    manageDirectDnsRecords = true,
    gcpCredentials?: Secret,
  ): Promise<string> {
    const config = this.loadDeploymentConfig({ deploymentSlot, manageDirectDnsRecords })
    return this.tfInit(src, this.resolveGcpCredentials(gcpCredentials), cloudflareToken, sshPublicKey, config)
      .withExec([
        "terraform", "plan",
        ...this.tfVars(config),
      ])
      .stdout()
  }

  /**
   * outputs — non-mutating.
   * Reads Terraform outputs from the configured remote state as JSON.
   */
  @func()
  async outputs(
    src: Directory,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    deploymentSlot = "blue",
    manageDirectDnsRecords = true,
    gcpCredentials?: Secret,
  ): Promise<string> {
    const config = this.loadDeploymentConfig({ deploymentSlot, manageDirectDnsRecords })
    return this.tfInit(src, this.resolveGcpCredentials(gcpCredentials), cloudflareToken, sshPublicKey, config)
      .withExec(["terraform", "output", "-json"])
      .stdout()
  }

  /**
   * deploy — production-mutating.
   * Runs `terraform apply` then bootstraps smallweb on the instance over SSH.
   * Returns the terraform outputs JSON on success.
   */
  @func()
  async deploy(
    src: Directory,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    sshPrivateKey: Secret,
    deploymentSlot = "blue",
    manageDirectDnsRecords = true,
    gcpCredentials?: Secret,
  ): Promise<string> {
    const config = this.loadDeploymentConfig({ deploymentSlot, manageDirectDnsRecords })
    const outputsJson = await this.tfInit(
      src,
      this.resolveGcpCredentials(gcpCredentials),
      cloudflareToken,
      sshPublicKey,
      config,
    )
      .withExec([
        "terraform", "apply", "-auto-approve",
        ...this.tfVars(config),
      ])
      .withExec(["terraform", "output", "-json"])
      .stdout()

    const outputs = JSON.parse(outputsJson) as Record<string, { value: string }>
    const ipv4 = outputs["instance_ipv4"]?.value
    if (!ipv4) {
      throw new Error(`terraform outputs missing instance_ipv4: ${outputsJson}`)
    }

    await this.sshBootstrap(src.file("scripts/bootstrap.sh"), ipv4, config.domain, sshPrivateKey)
    return outputsJson
  }

  /**
   * destroy — production-mutating.
   * Runs `terraform destroy` against production state.
   */
  @func()
  async destroy(
    src: Directory,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    deploymentSlot = "blue",
    manageDirectDnsRecords = true,
    gcpCredentials?: Secret,
  ): Promise<string> {
    const config = this.loadDeploymentConfig({ deploymentSlot, manageDirectDnsRecords })
    return this.tfInit(src, this.resolveGcpCredentials(gcpCredentials), cloudflareToken, sshPublicKey, config)
      .withExec([
        "terraform", "destroy", "-auto-approve",
        ...this.tfVars(config),
      ])
      .stdout()
  }

  /**
   * verify — non-mutating.
   * Runs external smoke checks against the deployed domain.
   */
  @func()
  async verify(domain = "tidelands.dev"): Promise<string> {
    const checks = `
set -euo pipefail

DOMAIN="${domain}"
PASS=0
FAIL=0

run_check() {
  local label="$1"
  local cmd="$2"
  local assert="$3"
  local result
  result=$(eval "$cmd" 2>&1) || true
  if echo "$result" | grep -q "$assert"; then
    echo "[PASS] $label"
    PASS=$((PASS + 1))
  else
    echo "[FAIL] $label"
    echo "  expected to find: $assert"
    echo "  got: $result"
    FAIL=$((FAIL + 1))
  fi
}

run_check "apex HTTP 200" \\
  "curl -sS --max-time 15 -o /dev/null -w '%{http_code}' https://$DOMAIN" \\
  "200"

run_check "health app HTTP 200" \\
  "curl -sS --max-time 15 https://health.$DOMAIN" \\
  '"ok":true'

run_check "Cloudflare proxy (CF-Ray header)" \\
  "curl -sS --max-time 15 -I https://$DOMAIN" \\
  "cf-ray"

run_check "wildcard routing (health subdomain via wildcard)" \\
  "curl -sS --max-time 15 -o /dev/null -w '%{http_code}' https://health.$DOMAIN" \\
  "200"

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
`

    return dag.container()
      .from("curlimages/curl:latest")
      .withExec(["sh", "-c", checks])
      .stdout()
  }

  /**
   * check — ephemeral-only (net non-mutating).
   * Runs Terratest suite against isolated resources named tidelane-test-<hex>.
   * Always destroys on exit. Pass preserveOnFailure=true to skip destroy on failure.
   * Full suite implemented in PLAN-185.
   */
  @func()
  async check(
    src: Directory,
    cloudflareToken: Secret,
    preserveOnFailure = false,
    gcpCredentials?: Secret,
  ): Promise<string> {
    const resolvedGcpCredentials = this.resolveGcpCredentials(gcpCredentials)
    const gcpProject = this.requiredEnv("GCP_PROJECT")
    let ctr = dag.container()
      .from("golang:1.22-bookworm")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)

    if (resolvedGcpCredentials !== null) {
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", resolvedGcpCredentials)
    } else {
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr
      .withEnvVariable("GCP_PROJECT", gcpProject)
      .withEnvVariable("PRESERVE_ON_FAILURE", preserveOnFailure ? "1" : "0")
      .withWorkdir("/workspace/test")
      .withExec(["go", "test", "-v", "-timeout", "30m", "./..."])
      .stdout()
  }

  /**
   * moduleCheck — preview-safe Dagger module build and smoke test.
   */
  @func()
  async moduleCheck(src: Directory): Promise<string> {
    return dag.container()
      .from("node:22-bookworm")
      .withDirectory("/workspace", src)
      .withWorkdir("/workspace")
      .withExec(["npm", "ci"])
      .withExec(["npm", "run", "build"])
      .withExec(["node", "--test", "module.smoke.test.mjs"])
      .stdout()
  }

  /**
   * smallwebBundle — creates a deployable working-tree bundle containing the
   * Smallweb root and the built Astro dist output as sibling directories.
   *
   * This is designed for quick Mutagen-based deployment: sync the bundle root
   * to the target machine, then run Smallweb with `--dir <bundle>/.smallweb-root`.
   *
   * If adminAuthorizedEmails is provided, it overrides the committed allowlist
   * for the exported bundle without requiring a code change in git.
   */
  @func()
  async smallwebBundle(
    @argument({ defaultPath: "../.smallweb-root", ignore: [".vscode/"] }) smallwebRoot: Directory,
    @argument({ defaultPath: "../dist" }) dist: Directory,
    adminAuthorizedEmails = "",
  ): Promise<Directory> {
    return dag.directory()
      .withDirectory(".smallweb-root", await this.renderSmallwebRoot(smallwebRoot, adminAuthorizedEmails))
      .withDirectory("dist", dist)
  }

  /**
   * smallwebMutagenProject — emits the quick-and-dirty Mutagen artifact set:
   * a deploy bundle plus a Mutagen configuration file.
   */
  @func()
  async smallwebMutagenProject(
    @argument({ defaultPath: "../.smallweb-root", ignore: [".vscode/"] }) smallwebRoot: Directory,
    @argument({ defaultPath: "../dist" }) dist: Directory,
    adminAuthorizedEmails = "",
  ): Promise<Directory> {
    return dag.directory()
      .withDirectory("bundle", await this.smallwebBundle(smallwebRoot, dist, adminAuthorizedEmails))
      .withFile("mutagen.yml", this.smallwebMutagenConfig())
      .withNewFile("README.txt", [
        "This directory is generated by `dagger call -m ./infra smallweb-mutagen-project`.",
        "",
        "Use `bundle/` as the local synchronization root.",
        "Run Smallweb on the remote machine with:",
        "  smallweb up --dir <remote-root>/.smallweb-root --domain tidelands.dev",
        "",
        "The `mutagen.yml` file sets one-way-replica mode and ignores VCS metadata.",
      ].join("\n"))
  }

  /**
   * smallwebMutagenConfig — returns a Mutagen configuration file for one-way
   * deployment from the generated bundle to a remote host.
   */
  @func()
  smallwebMutagenConfig(): File {
    return dag.directory()
      .withNewFile("mutagen.yml", this.renderMutagenConfig())
      .file("mutagen.yml")
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  /**
   * sshBootstrap connects to host as the smallweb user, waits for SSH to be
   * ready, copies bootstrap.sh from src, and runs it with the target domain.
   */
  private async sshBootstrap(
    bootstrapFile: File,
    host: string,
    domain: string,
    sshPrivateKey: Secret,
  ): Promise<string> {
    const sshFlags = "-o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /root/.ssh/id_ed25519"
    const target = `smallweb@${host}`

    return dag.container()
      .from("alpine:3.19")
      .withExec(["apk", "add", "--no-cache", "openssh-client"])
      .withMountedSecret("/root/.ssh/id_ed25519", sshPrivateKey)
      .withExec(["chmod", "600", "/root/.ssh/id_ed25519"])
      .withMountedFile("/bootstrap.sh", bootstrapFile)
      .withExec([
        "sh", "-c",
        `for i in $(seq 1 18); do
           ssh ${sshFlags} ${target} echo ready && break
           echo "waiting for SSH ($i/18)..." && sleep 5
           [ $i -eq 18 ] && echo "SSH timed out" && exit 1
         done`,
      ])
      .withExec(["scp", ...sshFlags.split(" "), "/bootstrap.sh", `${target}:/tmp/bootstrap.sh`])
      .withExec(["ssh", ...sshFlags.split(" "), target, `bash /tmp/bootstrap.sh ${domain}`])
      .stdout()
  }

  /**
   * tfInit returns a container with Terraform initialised against the GCS backend.
   *
   * gcpCredentials: when null, mounts host gcloud config for ADC. When provided,
   * sets GOOGLE_CREDENTIALS directly (key-fallback / CI mode).
   */
  private tfInit(
    src: Directory,
    gcpCredentials: Secret | null,
    cloudflareToken: Secret,
    sshPublicKey: Secret,
    config: DeploymentConfig,
  ): Container {
    let ctr = dag.container()
      .from("hashicorp/terraform:1.7")
      .withDirectory("/workspace", src)
      .withSecretVariable("CLOUDFLARE_API_TOKEN", cloudflareToken)
      .withSecretVariable("TF_VAR_cloudflare_api_token", cloudflareToken)
      .withSecretVariable("TF_VAR_ssh_public_key", sshPublicKey)

    if (gcpCredentials !== null) {
      // Key-fallback mode: explicit service account JSON key.
      ctr = ctr.withSecretVariable("GOOGLE_CREDENTIALS", gcpCredentials)
    } else {
      // Host-auth (ADC) mode: mount the host gcloud config so the GCP SDK and
      // Terraform provider resolve credentials via Application Default Credentials.
      ctr = ctr.withMountedDirectory(
        "/root/.config/gcloud",
        dag.host().directory(`${process.env.HOME}/.config/gcloud`),
      )
    }

    return ctr
      .withWorkdir("/workspace/terraform")
      .withExec([
        "terraform", "init", "-reconfigure",
        `-backend-config=bucket=${config.backendBucket}`,
        `-backend-config=prefix=${config.backendPrefix}`,
      ])
  }

  private tfVars(config: DeploymentConfig): string[] {
    return [
      `-var=gcp_project_id=${config.gcpProject}`,
      `-var=gcp_zone=${config.gcpZone}`,
      `-var=domain=${config.domain}`,
      `-var=cloudflare_zone_id=${config.cloudflareZoneId}`,
      `-var=instance_name=${config.instanceName}`,
      `-var=deployment_slot=${config.deploymentSlot}`,
      `-var=manage_direct_dns_records=${config.manageDirectDnsRecords}`,
    ]
  }

  private loadDeploymentConfig(overrides: Pick<DeploymentConfig, "deploymentSlot" | "manageDirectDnsRecords">): DeploymentConfig {
    return {
      backendBucket: this.requiredEnv("BACKEND_BUCKET"),
      backendPrefix: this.resolveBackendPrefix(overrides.deploymentSlot),
      gcpProject: this.requiredEnv("GCP_PROJECT"),
      cloudflareZoneId: this.requiredEnv("CLOUDFLARE_ZONE_ID"),
      gcpZone: process.env.GCP_ZONE ?? "us-central1-a",
      domain: process.env.DOMAIN ?? "tidelands.dev",
      instanceName: process.env.INSTANCE_NAME ?? "tidelane-smallweb",
      deploymentSlot: overrides.deploymentSlot,
      manageDirectDnsRecords: overrides.manageDirectDnsRecords,
    }
  }

  private resolveBackendPrefix(deploymentSlot: string): string {
    const explicit = process.env.BACKEND_PREFIX
    if (explicit && explicit.trim() !== "") {
      return explicit.replaceAll("{slot}", deploymentSlot)
    }

    const root = process.env.BACKEND_PREFIX_ROOT
    if (root && root.trim() !== "") {
      return `${root.replace(/\/+$/, "")}/${deploymentSlot}/terraform.tfstate`
    }

    throw new Error(
      "missing required env BACKEND_PREFIX or BACKEND_PREFIX_ROOT for Terraform state prefix",
    )
  }

  private requiredEnv(name: string): string {
    const value = process.env[name]
    if (!value || value.trim() === "") {
      throw new Error(`missing required env ${name}`)
    }

    return value
  }

  /**
   * Prefer an explicitly-passed secret, then fall back to Render/CI env.
   * This keeps the module callable both from local CLI and from a preview service
   * whose build command does not pass a dedicated --gcp-credentials flag.
   */
  private resolveGcpCredentials(gcpCredentials?: Secret): Secret | null {
    if (gcpCredentials) {
      return gcpCredentials
    }

    const envCredentials = process.env.GCP_CREDENTIALS_JSON
    if (envCredentials && envCredentials.trim() !== "") {
      return dag.setSecret("gcp-credentials", envCredentials)
    }

    return null
  }

  private async renderSmallwebRoot(smallwebRoot: Directory, adminAuthorizedEmails: string): Promise<Directory> {
    const config = JSON.parse(await smallwebRoot.file(".smallweb/config.json").contents()) as SmallwebRootConfig
    const authorizedEmails = this.parseAdminAuthorizedEmails(adminAuthorizedEmails)

    if (authorizedEmails.length > 0) {
      const adminApp = config.apps?.admin ?? {}
      config.apps = {
        ...(config.apps ?? {}),
        admin: {
          ...adminApp,
          authorizedEmails,
        },
      }
    }

    return smallwebRoot.withNewFile(".smallweb/config.json", `${JSON.stringify(config, null, 2)}\n`)
  }

  private parseAdminAuthorizedEmails(value: string): string[] {
    return value
      .split(/[\n,]/)
      .map((entry) => entry.trim())
      .filter((entry) => entry !== "")
  }

  private renderMutagenConfig(): string {
    return [
      "sync:",
      "  defaults:",
      "    mode: \"one-way-replica\"",
      "    ignore:",
      "      vcs: true",
      "      paths:",
      "        - \".smallweb-root/.smallweb/config.json\"",
      "        - \".smallweb-root/jules/.env\"",
      "        - \".smallweb-root/jules/data\"",
      "        - \".smallweb-root/linear-agent/.env\"",
      "        - \".smallweb-root/linear-agent/data\"",
      "",
    ].join("\n")
  }
}
