// Vendored from tutorial-app/src/lib/grant_state.pkl.ts so this lesson's
// WebContainer sandbox (a self-contained project, no import across the
// _files boundary) can run the exact same code this terminal's own
// `npm test` and the outer app both use.
/* Vendored (manual copy, no shared package boundary) from
 * capability-spike/ts/grant_state.pkl.ts -- re-run
 * `npx @pkl-community/pkl-typescript -o ts pkl/GrantState.pkl` there and
 * re-copy on schema changes. */
/* This file was generated by `pkl-typescript` from Pkl module `grantState`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// Supervisor-owned approval ledger. Rendered by supervisor/state.go --
// do not hand-edit; do not let worker code write this file.
export interface GrantState {
  approvedGrants: Map<string, Grant>
}

// Ref: Pkl class `grantState.Grant`.
export interface Grant {
  factID: string

  vault: string

  approved: boolean
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a GrantState
export const loadFromPath = async (path: string): Promise<GrantState> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<GrantState> =>
  evaluator.evaluateModule(source) as Promise<GrantState>;
