// Vendored from tutorial-app/src/lib/inventory.pkl.ts so this lesson's
// WebContainer sandbox (a self-contained project, no import across the
// _files boundary) can run the exact same code this terminal's own
// `npm test` and the outer app both use.
/* Vendored (manual copy, no shared package boundary) from
 * capability-spike/ts/inventory.pkl.ts -- re-run
 * `npx @pkl-community/pkl-typescript -o ts pkl/Inventory.pkl` there and
 * re-copy on schema changes. */
/* This file was generated by `pkl-typescript` from Pkl module `inventory`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// Declared-vs-observed inventory checking, for this lesson's capability-
// acquisition scenario (see Inventory.test.pkl and the tutorial-app lesson
// it feeds). `VaultSpec` mirrors
// .dagger/internal/devenv-base/pkl/Vaults.pkl's class of the same name,
// field-for-field; `ObservedVault`/`ObservedInventory` formalize the shape
// .dagger/internal/devenv-base/hk/capture-vault-inventory.sh writes to
// build/vaults-observed.json, which
// .dagger/internal/devenv-base/pkl/Vaults.test.pkl currently reads as
// untyped `Dynamic`. That directory's own CLAUDE.md reserves it for
// container-use environments, so these classes are duplicated here by
// hand, not imported -- keep them in sync with the source on drift, same
// discipline tk-evidence-exporter/ts/evidence.pkl.ts's own header already
// documents for its vendoring into tutorial-app.
export interface Inventory {
}

// Ref: Pkl class `inventory.VaultSpec`.
// A task's declared requirement: which vault, and which items in it, it
// needs.
export interface VaultSpec {
  name: string

  items: Array<string>
}

// Ref: Pkl class `inventory.ObservedVault`.
// One vault's contents as actually observed (captured from the real
// system), not asserted.
export interface ObservedVault {
  name: string

  items: Array<string>
}

// Ref: Pkl class `inventory.ObservedInventory`.
// The full observed inventory a `VaultSpec` requirement is checked
// against. Mirrors vaults-observed.json's top-level `{vaults: [...]}`
// shape.
export interface ObservedInventory {
  vaults: Array<ObservedVault>
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a Inventory
export const loadFromPath = async (path: string): Promise<Inventory> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<Inventory> =>
  evaluator.evaluateModule(source) as Promise<Inventory>;
