// Vendored from tutorial-app/src/lib/reconcile.pkl.ts so this lesson's
// WebContainer sandbox (a self-contained project, no import across the
// _files boundary) can run the exact same code this terminal's own
// `npm test` and the outer app both use.
/* Vendored (manual copy, no shared package boundary) from
 * capability-spike/ts/reconcile.pkl.ts -- re-run
 * `npx @pkl-community/pkl-typescript -o ts pkl/Reconcile.pkl` there and
 * re-copy on schema changes. */
/* This file was generated by `pkl-typescript` from Pkl module `reconcile`. */
/* DO NOT EDIT! */
/* istanbul ignore file */
/* eslint-disable */
import * as pklTypescript from "@pkl-community/pkl-typescript"

// Ref: Module root.
// The alignment axiom, written as Pkl instead of only as Go.
//
// `reconcile/reconcile.go`'s `Check` already reconciles three
// representations of the same capability acquisition:
//
//     worker fact requesting the capability
//             ↕
//     supervisor-approved grant
//             ↕
//     observed PROTON_PASS_AGENT_REASON / materialization
//
// This module states the same invariant as a function, so it can be
// exercised by `pkl test` with no Go toolchain, no Proton Pass
// credentials, and no `build/proton-observed.jsonl` on disk -- see
// `Reconcile.test.pkl`, which is what actually makes this file an
// instrument rather than a description.
//
// Why it matters that this is an *axiom* and not a *fact*: a fact
// records observed state, and every value `check()` takes is a fact
// (what the worker asked for, what the supervisor decided, what the
// runtime recorded). `check()` itself is the expectation about what
// must follow if those three facts describe one coherent world. Running
// it is what turns that expectation into an observable diagnostic.
//
// `boundary-bypassed` is the flag this whole module exists for. Every
// other kind here fires on a divergence you could also have noticed by
// reading the values. That one fires on a fact file that *passes*
// `pkl test` -- see `worker/fixtures_invalid/bypassed_gate.pkl` and
// `TestBypassedGatePassesPklTestButFlaggedByReconciliation` in
// `demo_test.go`, a committed Go test whose entire assertion is that
// the green result means nothing. A green test is evidence about the
// test, not about the world it was supposed to be watching.
export interface Reconcile {
  // Kept as constants rather than inline strings so the Go `FlagKind`
  // values, this module, and tutorial-app's `reconcileCheck.ts` replay
  // can be compared literally instead of by eye.
  uNAPPROVEDMATERIALIZATION: pklTypescript.Any

  mISSINGMATERIALIZATION: pklTypescript.Any

  rEASONMISMATCH: pklTypescript.Any

  bOUNDARYBYPASSED: pklTypescript.Any

  // The one substring that distinguishes a fact that asked the supervisor
  // a question from a fact that answered it itself.
  gATECALL: pklTypescript.Any
}

// Ref: Pkl class `reconcile.Grant`.
// Mirrors `GrantState.pkl`'s class of the same name, field-for-field.
// Duplicated rather than imported on purpose: `GrantState.pkl` is
// supervisor-rendered and git-ignored (see `.gitignore`'s own comment),
// so importing it would make this module unevaluatable in a fresh
// checkout -- and `check()` takes the grants it reconciles against as an
// argument anyway, exactly as `reconcile.Check` takes `statePath`. Same
// duplication discipline `Inventory.pkl`'s header already documents for
// its copy of `Vaults.pkl`'s `VaultSpec`; keep the two in sync on drift.
export interface Grant {
  factID: string

  vault: string

  approved: boolean
}

// Ref: Pkl class `reconcile.Observation`.
// One recorded Proton Pass operation, mirroring
// `runtime.Observation`. `reason` is the literal
// `PROTON_PASS_AGENT_REASON` value the operation actually carried --
// the field that can drift in a real integration. `factID` is metadata
// the recorder chose, so checking it alone would validate nothing.
export interface Observation {
  factID: string

  vault: string

  reason: string
}

// Ref: Pkl class `reconcile.FactFile`.
// One worker-owned fact file, carried by its own text rather than its
// path, because this module has no filesystem access and the check is a
// structural one over the source anyway. `reconcile.FactFile` carries
// the path and reads the bytes; the predicate applied to them is the
// same.
export interface FactFile {
  factID: string

  path: string

  source: string
}

// Ref: Pkl class `reconcile.Flag`.
export interface Flag {
  kind: string

  factID: string

  detail: string
}

// LoadFromPath loads the pkl module at the given path and evaluates it into a Reconcile
export const loadFromPath = async (path: string): Promise<Reconcile> => {
  const evaluator = await pklTypescript.newEvaluator(pklTypescript.PreconfiguredOptions);
  try {
    const result = await load(evaluator, pklTypescript.FileSource(path));
    return result
  } finally {
    evaluator.close()
  }
};

export const load = (evaluator: pklTypescript.Evaluator, source: pklTypescript.ModuleSource): Promise<Reconcile> =>
  evaluator.evaluateModule(source) as Promise<Reconcile>;
